services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./external:/app/data

    environment:
      - DATABASE_PATH=/app/data/db/habits.db
      - CONFIGURATION_PATH=/app/data/config
      - LOG_LEVEL=INFO
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000

volumes:
  habit-data: