services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/habits.db
      - LOG_LEVEL=INFO

volumes:
  habit-data: