version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  # <-- Montar directorio data para persistencia
    environment:
      - DATABASE_PATH=/app/data/habits.db  # <-- Ruta dentro del contenedor

volumes:
  habit-data: