version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(module)s:%(lineno)d] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: standard
    stream: ext://sys.stdout

loggers:
  business:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: ${LOG_LEVEL}
  handlers: [console]